### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by troncoso** [Handiwork/autumn-electron-ipc#5]
Hi there. Do you have a working example for this library? I can't get it to work. I keep getting this error:

`An object could not be cloned`

Based on my research, this is due to this: https://www.electronjs.org/docs/latest/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception

**Comment by Handiwork** [comment]
Hi. Thanks for your feedback. I'm sorry that this lib is not well documented and tested. In fact, the [test](https://github.com/Handiwork/autumn-electron-ipc/tree/v1.0.6/test) directory is a working example. This lib, as a wrapper for electron IPC, will throw exceptions when transferring [unsupported types](https://www.electronjs.org/docs/latest/api/web-contents#contentssendchannel-args).

**Comment by troncoso** [comment]
Thank you for the response. I've looked over the examples, but they are very basic and don't cover what I consider a very common usage. I have my directories like this:

`/main`
`/preload`
`/shared`
`/renderer`

In my `/shared`, I have:

```typescript
import type { Database } from '../models/Database'
import { createR2MApiTs } from 'autumn-electron-ipc'

export interface DatabaseService {
	find(): Promise<Database[]>
	// ...
}

export const databaseService = createR2MApiTs<DatabaseService>('database')
```

In `/main` I register this service:

```typescript
import { DatabaseServiceImpl } from './DatabaseServiceImpl'
import { databaseService } from '@shared/api/DatabaseService'

export function initializeApi() {
	databaseService.plugInMain(new DatabaseServiceImpl())
}
```

And in `/preload`, I try to expose the service to the renderer:

```typescript
import { contextBridge } from 'electron'
import { databaseService } from '../../shared/api/DatabaseService'

const api = {
	database: databaseService.getClient()
}

contextBridge.exposeInMainWorld('api', api)
```

It seems that I cannot pass the service to the renderer because it is a `Proxy` object. I tried passing the actual `databaseService` object, but it becomes empty on the other side.

Do you have a suggestion for the right way to do this? I do not want to turn on `nodeIntegration` so I have to use the `preload` script.

**Comment by Handiwork** [comment]
It does not matter to keep `nodeIntegration` off. Just  turn off `contextIsolation` (default is `true` since Electron 12) and expose created clients to `window`. [Explanation and examples can be found here.](https://github.com/electron/electron/blob/main/docs/tutorial/context-isolation.md) Since you already wrap system calls to proxy handlers, it's safe to disable context isolation between `preload` and `renderer`.

**Comment by troncoso** [comment]
Ah, I see. I changed `contextIsolation` to false and updated the `preload` script to this:

```typescript
window.api = {
	database: databaseService.getClient()
}
```
That seems to have done the trick. Thanks a lot!

**Comment by Handiwork** [comment]
np.
